# xls to csv

In [ ]:
# House Sale Price_Monthly_Trend
# file name = house_sale_price_monthly_trend

In [ ]:
# # pip 설치 내용
# pip install xlrd
# pip install openpyxl
# pip install pandas

In [2]:
# import
import pandas as pd

In [3]:
# test 1
xls = pd.read_excel("./EDA_file/house_sale_price_monthly_trend.xls")
xls.to_csv("./EDA_file/house_sale_price_monthly_trend.csv")

In [5]:
# verify
data = pd.read_csv("./EDA_file/house_sale_price_monthly_trend.csv")
data.head(10)

,Unnamed: 0,통계표명:,주택매매가격 동향,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Unnamed: 198,Unnamed: 199,Unnamed: 200
0,0,단위:,%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,200601월,200602월,200603월,200604월,200605월,200606월,200607월,200608월,...,202111월,202112월,202201월,202202월,202203월,202204월,202205월,202206월,202207월,202208월
2,2,전국,0.3,0.5,0.6,0.9,1.0,0.5,0.2,0.2,...,0.6,0.3,0.1,0.0,0.0,0.1,0.0,0.0,-0.1,-0.3
3,3,수도권,0.5,0.7,1.0,1.4,1.7,0.9,0.4,0.5,...,0.8,0.3,0.1,0.0,0.0,0.0,0.0,0.0,-0.1,-0.4
4,4,서울,0.6,0.8,1.2,1.5,1.5,0.7,0.3,0.4,...,0.6,0.3,0.0,0.0,0.0,0.0,0.0,0.0,-0.1,-0.2
5,5,강남,1.0,1.2,1.8,2.3,2.2,0.8,0.3,0.2,...,0.6,0.3,0.1,0.0,0.0,0.1,0.1,0.0,0.0,-0.2
6,6,강북,0.2,0.3,0.5,0.7,0.7,0.6,0.4,0.5,...,0.5,0.2,0.0,-0.1,0.0,0.0,0.0,0.0,-0.1,-0.3
7,7,출처:,한국부동산원「전국주택가격동향조사」,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,주석:,월별 주택 매매가격 증감률,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data

,Unnamed: 0,통계표명:,주택매매가격 동향,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Unnamed: 198,Unnamed: 199,Unnamed: 200
0,0,단위:,%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,200601월,200602월,200603월,200604월,200605월,200606월,200607월,200608월,...,202111월,202112월,202201월,202202월,202203월,202204월,202205월,202206월,202207월,202208월
2,2,전국,0.3,0.5,0.6,0.9,1.0,0.5,0.2,0.2,...,0.6,0.3,0.1,0.0,0.0,0.1,0.0,0.0,-0.1,-0.3
3,3,수도권,0.5,0.7,1.0,1.4,1.7,0.9,0.4,0.5,...,0.8,0.3,0.1,0.0,0.0,0.0,0.0,0.0,-0.1,-0.4
4,4,서울,0.6,0.8,1.2,1.5,1.5,0.7,0.3,0.4,...,0.6,0.3,0.0,0.0,0.0,0.0,0.0,0.0,-0.1,-0.2
5,5,강남,1.0,1.2,1.8,2.3,2.2,0.8,0.3,0.2,...,0.6,0.3,0.1,0.0,0.0,0.1,0.1,0.0,0.0,-0.2
6,6,강북,0.2,0.3,0.5,0.7,0.7,0.6,0.4,0.5,...,0.5,0.2,0.0,-0.1,0.0,0.0,0.0,0.0,-0.1,-0.3
7,7,출처:,한국부동산원「전국주택가격동향조사」,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,주석:,월별 주택 매매가격 증감률,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN